version: '3.3'

services:
  app:
    build: .
    command: ./auth_jwt
    ports:
      - 8080:8080
    depends_on:
      - mdb
    restart: always

  mdb:
    image: mongo:4.4.6
    ports:
      - 27100:27017
    restart: always
    env_file:
      - .env